### PR TITLE
Fix number implementations are never used

### LINKED ISSUE #23: Behaviour of f64 formatting differs from std::fmt
via `std::fmt` a number like `42f64` formatted via `hello {:.3}` would look like `hello 42.000`,
but formated via strfmt it results in `hello 42`

is this behaviour intended or described anywhere?

### PR DESCRIPTION
**Pull request by Hero9909**
These commits contain a new trait to use the correct types when formatting.
This closes #23. 

while writing this I think about mixed values and I'm unsure if there are downsides that might follow this usage.

Anyway, while writing I noticed some warnings that could be removed without any downside, while improving readability, moving on to the newer syntax.

### CODE REVIEW

**Comment by vitiral** [comment]
Haven't looked yet, but how much work is it to make the reformatting in a
separate commit?

I tend to want to keep feature changes isolated from refactoring

File: src/fmtnum.rs [hunk 1]
```diff
@@ -123,3 +123,13 @@ macro_rules! fmtfloat {
             }
         })*)
 }
+
+macro_rules! fmttype {
```
Comment (vitiral) [inline src/fmtnum.rs:127]: is this the right place for this?

File: src/lib.rs [hunk 2]
```diff
@@ -24,10 +24,30 @@ pub use types::{Alignment, FmtError, Result, Sign};
...
+    fn do_format(&self, f: &mut Formatter) -> Result<()> {
+        f.str(self)
+    }
+}
+
+fmttype!(u8 i8 u16 i16 u32 i32 u64 i64 usize isize);
+fmttype!(f32 f64);
+
 /// Rust-style format a string given a `HashMap` of the variables.
-pub fn strfmt<K, T: fmt::Display>(fmtstr: &str, vars: &HashMap<K, T>) -> Result<String>
```
Comment (vitiral) [inline src/lib.rs:28]: So this is changing the type API of the library, right?

With these changes, the library will no longer allow just any type which implements `Display`, folks will have to specifically implement `TypeFormatting` for their custom types, correct?

File: src/fmtnum.rs (hunk 1 above)
Comment (Hero9909) [reply src/fmtnum.rs:127]: it generates the definition of what formatter should be used for which type of numbers, sounds good to me, but I'm not afraid to move it elsewhere if you want me to.

File: src/lib.rs (hunk 2 above)
Comment (Hero9909) [reply src/lib.rs:28]: Correct, but only if you would like to pass types to the Formatter where we don't know which Formatter should resolve this. I see what you want here and I got an idea of how to fix this, ill try to update as soon as I get more time.

Currently I am unavailable until 1 Aug.

**Comment by Hero9909** [comment]
I ended up splitting this into two parts and keeping the old behavior and adding an _ext function for formatting numbers and custom types. I've discussed this with a good friend and we see no other way for this. But different from the previous commitment, basic usage should be the same.

File: src/lib.rs (hunk 2 above)
Comment (vitiral) [reply src/lib.rs:28]: I'm wondering if there is a way to auto-implement `TypeFormatting` for any type which implements `Display`?

https://stackoverflow.com/a/29256897/1036670

```
impl<D> TypeFormatting for D
where
    D: Display,
{
    fn do_format(&self, f:&mut Formatter) -> Result<()> {
        f.str(format!(self))
    }
}
```

Something like that... my rust is a bit... rusty.

Comment (vitiral) [reply src/lib.rs:28]: If we did the above, I _believe_ we could get rid of `strfmt_ext` but also not break backwards compatibility? If you think I'm right I'd appreciate some tests to prove it!

And thanks for doing this work, I really appreciate it. I just want to make sure the API is as good as it can be.

Comment (Hero9909) [reply src/lib.rs:28]: That's the problem, this generic trait implementation would also implement the behavior for other types, like the already implemented stuff for f64,f32,u8,i8.... I don't know any trait that allows us to disguise between primitive and non-primitive, as well as the question mentioned in your StackOverflow Discussion is "why should Rust?".

And to say this clearly, I appreciate this review. I'm total with you, the API should be as good as it can be.

**Comment by Hero9909** [comment]
Another solution could be to offer a macro that implements the trait for types that already have a Display impl. 

We still could use things like derive macros or feature flags, but I don't see anything that brings us closer to the ideal solution.

**Comment by vitiral** [comment]
after consideration, I think this should be a breaking change considering that it is fixing a bug. I'm also remembering some of the problem space. The main issue is that [Display](http://web.mit.edu/rust-lang_v1.26.0/arch/amd64_ubuntu1404/share/doc/rust/html/std/fmt/trait.Display.html) takes in a **struct** `Formatter` object. If that was a trait instead, then we wouldn't have to do any of these shenanigans.

Anyway, all water under the bridge. On that point though, your `TypeFormatting` is really just a re-implementation of `Display` using our own `Formatter`. Let's make the names match this fact:

- rename `TypeFormatting` -> `DisplayStr` and move into `lib.rs`. 
  - rename method `do_format` -> `display_str`
  - rename `fmttype` macro to something like `display_str_impl` and move into `lib.rs`
- in `strfmt` function, replace `Display` with `DisplayStr`, to pick up your changes. I think this was your original approach and will be a breaking change.
- create a new method `strfmt_display` which still uses `Display`, essentially converting everything to a `String`. This will allow folks to easily migrate if they depend on the `Display` implementation.

Thoughts?

**Comment by Hero9909** [comment]
Sounds good, then let's get this on the road:

- [ ] rename `TypeFormatting` and functions 
- [ ] rename macros
- [ ] change signature of `strfmt` to match new requirements
- [ ] create legacy `strfmt` named `strfmt_display`
- [ ] Add Documentation
- [ ] add tests for legacy

**Comment by vitiral** [comment]
Sounds good, you rock!

**Comment by Hero9909** [comment]
same legacy convention for formatter? eg format_display?

**Comment by vitiral** [comment]
You mean the `trait Format`? Yes, I think you should take in `DisplayStr` instead of display, and there can be a `format_display` method like you said.

File: src/lib.rs [hunk 3]
```diff
@@ -47,28 +69,71 @@ where
...
+                return Err(new_key_error(fmt.key));
+            }
+        };
+
+        v.do_format(&mut fmt)
+    };
+    strfmt_map(fmtstr, &formatter)
+}
+
 pub trait Format {
```
Comment (Hero9909) [inline src/lib.rs:96]: Sorry, I'll make this as clear as I can explain with my limited English. 
The marked trait ist defining functions for `str` and `String` where usage would be `"{Zero}".format(&vars)`.
By adding a legacy function here named `strfmt_display` it would make sense to add a similar extension to allow a usage like `"{Zero}".format_display(&vars)` as either the original signature would change from  `format<K, D: fmt::Display>(&self, vars: &HashMap<K, D>) -> Result<String>` to `format<K, D: DisplayStr>(&self, vars: &HashMap<K, D>) -> Result<String>` or the body would change and default to use the legacy code.

Don't hesitate to ask, sometimes I think way to complicated and by reading these lines I wrote I'm not sure if it gets clear what problem ist the cause for this..

Comment (vitiral) [reply src/lib.rs:96]: Thanks for clarifying. I agree with you, there should be two functioned defined by `Format`:


```
trait Format {
  fn format<K, D: DisplayStr>(&self, vars: &HashMap<K, D>) -> Result<String>

  fn format_display<K, D: Display>(&self, vars: &HashMap<K, D>) -> Result<String>
```

**Comment by Hero9909** [comment]
Okay, so I was realizing that one big commit wasn't one of my greatest ideas, sry.

Second I added some documentation and deprecation marks. As these changes contain a change of the API I thought it should increment the minor number at least.

File: src/lib.rs [hunk 4]
```diff
@@ -47,28 +102,106 @@ where
...
+    /// ```
+    /// use std::collections::HashMap;
+    /// use std::f64::consts::PI;
+    /// use strfmt::Format;
+    ///
+    /// let mut my_vars: HashMap<String, f64> = HashMap::new();
+    /// my_vars.insert("Alpha".to_string(),42.0);
+    /// my_vars.insert("Beta".to_string(),PI);
+    ///
+    /// let result = "|{Alpha}|{Beta:<5.2}|".format(&my_vars);
```
Comment (vitiral) [inline src/lib.rs:157]: for examples just use `?`.  So this would be `println!("|{Alpha}|{Beta:<5.2}|".format(&my_vars)?)`

File: src/tests/float.rs [hunk 5]
```diff
@@ -0,0 +1,34 @@
+use std::collections::HashMap;
+use ::{FmtError, Format};
+
+#[test]
+fn test_fmt_float64() -> Result<(),FmtError> {
+    let mut vars: HashMap<String, f64> = HashMap::new();
+    vars.insert("Zero".to_string(), 0.0);
+    vars.insert("One".to_string(), 10.0 / 3.0);
```
Comment (vitiral) [inline src/tests/float.rs:8]: rename `Three`?

File: src/tests/float.rs [hunk 6]
```diff
@@ -0,0 +1,34 @@
...
+    assert_eq!("0.00 ".to_string(),"{Zero:<5.2}".format(&vars)?);
+
+    Ok(())
+}
+
+#[test]
+fn test_fmt_float32() -> Result<(),FmtError> {
+    let mut vars: HashMap<String, f32> = HashMap::new();
+    vars.insert("Zero".to_string(), 0.0);
+    vars.insert("One".to_string(), 10.0 / 3.0);
```
Comment (vitiral) [inline src/tests/float.rs:24]: ditto, rename "Three"

**Review by vitiral — APPROVED** [review]

File: src/tests/float.rs (hunk 6 above)
Comment (Hero9909) [reply src/tests/float.rs]: jup, done

File: src/lib.rs (hunk 4 above)
Comment (Hero9909) [reply src/lib.rs]: oh, sure that's much better

**Comment by vitiral** [comment]
pushed to crates.io after a few minor fixes from me

https://crates.io/crates/strfmt

**Comment by Hero9909** [comment]
ah, the version number. great, that was intended by the way, as it's your project and therefore your decision when things will get a release. 

The next thing on my list is the refactoring to remove warnings.

**Comment by vitiral** [comment]
I ran `cargo fmt` and removed lint warnings before I released, sorry :smile:
